plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "net.waldrip.hop.demo"
    compileSdk = 34

    defaultConfig {
        applicationId = "net.waldrip.hop.demo"
        minSdk = 29 // L2CAP CoC (createInsecureL2capChannel) requires API 29+
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"
    }

    buildFeatures { compose = true }
    composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = "1.8" }

    // Generated by android/build-aar.sh (gitignored):
    //   ../generated/kotlin/uniffi/hop_ffi/hop_ffi.kt   (the UniFFI bindings)
    //   ../generated/jniLibs/<abi>/libhop_ffi.so        (the native libraries)
    sourceSets["main"].java.srcDir("../generated/kotlin")
    sourceSets["main"].jniLibs.srcDir("../generated/jniLibs")
}

dependencies {
    // UniFFI-generated Kotlin uses JNA; the @aar variant bundles its native libs.
    implementation("net.java.dev.jna:jna:5.14.0@aar")

    implementation(platform("androidx.compose:compose-bom:2024.06.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.0")
    implementation("androidx.core:core-ktx:1.13.1")

    // Cloud relay bearer: WebSocket (path B, wss:// → Cloud Run) + the okio ByteString
    // it speaks. Raw-TCP relay (path A) uses plain java.net.Socket.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
}
