// swift-tools-version:5.9
import PackageDescription

// HopDriver — the reusable Apple driver for the Hop runtime.
//
// It owns the whole Hop bearer (BLE/Wi-Fi/LAN/relay transports + the node) so a host app
// is a thin consumer. Multiplatform: iOS 16 (the demo app) + macOS 13 (the `hopmac` headless
// BLE-central test node). The generated FFI bindings + the prebuilt xcframework live inside the
// package (regenerated by apple/build-xcframework.sh); both are gitignored build artifacts.
let package = Package(
    name: "HopDriver",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "HopDriver", targets: ["HopDriver"]),
        .executable(name: "hopmac", targets: ["hopmac"]),
        .executable(name: "relaymac", targets: ["relaymac"]),
    ],
    // The shared cross-platform transport layer (HopBearers), a sibling SwiftPM package. The driver
    // pulls in the contract/registry (Core) + the BLE and LAN bearers; the new shared-bearer path
    // (Config.useSharedBearers, default on) forms BLE+LAN links through these, with the legacy in-driver
    // HopLink/GattDataLink/LanLink kept as a flag-off fallback.
    dependencies: [
        .package(path: "../HopBearers"),
    ],
    targets: [
        // The Rust core, compiled to a static lib and packaged as an xcframework (ios-arm64,
        // ios-sim, macos). Built by apple/build-xcframework.sh.
        .binaryTarget(name: "hop_ffiFFI", path: "Frameworks/HopFFI.xcframework"),

        // The Objective-C exception catcher (CoreBluetooth raises NSExceptions Swift can't catch).
        // A Clang target with an include/ umbrella header — replaces the app's bridging header.
        .target(name: "HopObjC"),

        // The UniFFI-generated Swift API (hop_ffi.swift), which imports the binary module.
        .target(name: "HopFFIBindings", dependencies: ["hop_ffiFFI"]),

        // The bearer + transports.
        .target(name: "HopDriver", dependencies: [
            "HopFFIBindings", "HopObjC",
            .product(name: "HopBearerCore",  package: "HopBearers"),
            .product(name: "HopBearerBle",   package: "HopBearers"),
            .product(name: "HopBearerLan",   package: "HopBearers"),
            .product(name: "HopBearerRelay", package: "HopBearers"),
        ]),

        // Headless macOS BLE-central node driving the driver in `.centralOnly` mode.
        .executableTarget(name: "hopmac", dependencies: ["HopDriver"]),
        // Headless macOS RELAY-ONLY client (`.relayOnly` mode) — no BLE/LAN/Wi-Fi, relay path only.
        .executableTarget(name: "relaymac", dependencies: ["HopDriver"]),
    ]
)
