// swift-tools-version:5.9
import PackageDescription

// Hop — the thin idiomatic Swift face of libhop's C ABI (../../hop.h). It is a GENERATED-contract
// wrapper: `CHop` is a system-library module over the cbindgen header (regenerated by
// core/hop-ffi/regen-header.sh, so it can't drift from the Rust), and `Hop` wraps those C calls in
// Swift types. Bearers and apps depend on `Hop`, never on the raw header.
//
// Linking libhop: this package does NOT hardcode a library path — the consumer (or smoke.sh) passes
// `-Xlinker -L<dir> -Xlinker -lhop_ffi`. The north-star packages libhop as an xcframework for device
// builds; this keeps the macOS dev/test loop path-free.
let package = Package(
    name: "Hop",
    platforms: [.macOS(.v13), .iOS(.v16)],
    products: [
        .library(name: "Hop", targets: ["Hop"]),
    ],
    targets: [
        .systemLibrary(name: "CHop", path: "Sources/CHop"),
        .target(name: "Hop", dependencies: ["CHop"]),
        .executableTarget(name: "HopSmoke", dependencies: ["Hop"]),
        .executableTarget(name: "RuntimeSmoke", dependencies: ["Hop"]),
    ]
)
