// swift-tools-version:5.9
import PackageDescription
import Foundation

// SELF-ADAPTING DEPENDENCIES. This package is exported to the hop-driver-apple mirror, where the SDK and
// the bearers are NOT on disk: every `.package(path: "../../../...")` below pointed outside the mirror
// repository, so the published package could not be resolved by anyone. (`hop-driver-apple` has cut
// tagged releases at v0.0.1 and v0.0.2 in that state.) A manifest is real Swift, so it detects which
// tree it is in and depends on siblings locally, published packages in the mirror. That is the same
// approach bearers/android uses for its shim, and it avoids teaching copybara another transform.
//
// Paths resolve against #filePath, not the process working directory, which SwiftPM does not promise.
//
// Note the SHAPE differs between the two, not just the spelling: in the monorepo each bearer is its own
// package (five path dependencies), while the mirror consumes the single hop-bearers-apple package that
// exposes all five as PRODUCTS. A path dependency's identity is its directory name, a remote one's is
// the repository name, so the product references are computed rather than written twice.
private let manifestDirectory = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
private let repositoryRoot = manifestDirectory.appendingPathComponent("../../..").standardized
private func onDisk(_ relative: String) -> Bool {
    FileManager.default.fileExists(
        atPath: repositoryRoot.appendingPathComponent(relative).appendingPathComponent("Package.swift").path
    )
}
private let inMonorepo = onDisk("sdk/apple") && onDisk("bearers/apple/HopBearerBle")

private let bearerNames = [
    "HopBearerBle",
    "HopBearerLan",
    "HopBearerMultipeer",
    "HopBearerRelay",
    "HopBearerMeshtastic",
]

private let sdkPackage = inMonorepo ? "apple" : "hop-sdk-apple"
private func bearerPackage(_ bearer: String) -> String { inMonorepo ? bearer : "hop-bearers-apple" }

private let packageDependencies: [Package.Dependency] = inMonorepo
    ? [.package(path: "../../../sdk/apple")]
        + bearerNames.map { .package(path: "../../../bearers/apple/\($0)") }
    : [
        .package(url: "https://github.com/hopmesh/hop-sdk-apple.git", from: "0.0.2"),
        .package(url: "https://github.com/hopmesh/hop-bearers-apple.git", from: "0.0.2"),
    ]

private let driverDependencies: [Target.Dependency] =
    ["HopFFIBindings", "HopObjC", .product(name: "HopContract", package: sdkPackage)]
        + bearerNames.map { .product(name: $0, package: bearerPackage($0)) }

// HopDriver, the reusable Apple driver for the Hop runtime (north-star drivers/apple location).
//
// It owns the whole Hop bearer (BLE/Wi-Fi/LAN/relay transports + the node) so a host app
// is a thin consumer. Multiplatform: iOS 16 (the demo app) + macOS 13 (the `hopmac` headless
// BLE-central test node). The generated FFI bindings + the prebuilt xcframework live inside the
// package (regenerated by tools/build-xcframework.sh); both are gitignored build artifacts.
let package = Package(
    name: "HopDriver",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "HopDriver", targets: ["HopDriver"]),
        .executable(name: "hopmac", targets: ["hopmac"]),
        .executable(name: "relaymac", targets: ["relaymac"]),
    ],
    // The transport layer is the four INDEPENDENT bearer packages (bearers/apple/*), each binding the
    // pure-Swift HopContract (from sdk/apple). BLE + LAN + cloud relay links now form ONLY through
    // those bearers via the BearerManager (there is no `Config.useSharedBearers` flag and no in-driver
    // HopLink/GattDataLink/LanLink fallback, those were deleted in the cutover). Multipeer (Wi-Fi P2P)
    // and the direct hops:// endpoints remain in-driver; the long-lived IOThread is retained purely as the
    // shared BLE runloop the BleBearer schedules its L2CAP streams + timers on. The old apple/HopBearers
    // package is gone.
    // The node API stays on UniFFI (HopFFI.xcframework). The bearers bind HopContract (pure Swift, no
    // libhop), so there is no double-link of the Rust core. Siblings in the monorepo, published
    // packages in the mirror; see the note at the top of this file.
    dependencies: packageDependencies,
    targets: [
        // The Rust core, compiled to a static lib and packaged as an xcframework (ios-arm64,
        // ios-sim, macos). Built by tools/build-xcframework.sh.
        .binaryTarget(name: "hopFFI", path: "Frameworks/HopFFI.xcframework"),

        // The Objective-C exception catcher (CoreBluetooth raises NSExceptions Swift can't catch).
        // A Clang target with an include/ umbrella header; replaces the app's bridging header.
        .target(name: "HopObjC"),

        // The UniFFI-generated Swift API (hop.swift), which imports the binary module.
        .target(name: "HopFFIBindings", dependencies: ["hopFFI"]),

        // The bearer + transports.
        .target(name: "HopDriver", dependencies: driverDependencies),

        // Headless macOS BLE-central node driving the driver in `.centralOnly` mode.
        .executableTarget(name: "hopmac", dependencies: ["HopDriver"]),
        // Headless macOS RELAY-ONLY client (`.relayOnly` mode), no BLE/LAN/Wi-Fi, relay path only.
        .executableTarget(name: "relaymac", dependencies: ["HopDriver"]),

        // sec-priv-02: the Keychain-backed identity/db-key store, tested headlessly on macOS (the
        // generic-password path works without a device; SE wrapping no-ops when the Enclave is absent).
        .testTarget(name: "HopDriverTests", dependencies: ["HopDriver"]),
    ]
)
