plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "net.waldrip.hop.driver"
    compileSdk = 34

    defaultConfig {
        minSdk = 29 // L2CAP CoC (createInsecureL2capChannel) requires API 29+
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = "1.8" }

    // Generated by android/build-aar.sh (gitignored):
    //   ../generated/kotlin/uniffi/hop_ffi/hop_ffi.kt   (the UniFFI bindings)
    //   ../generated/jniLibs/<abi>/libhop_ffi.so        (the native libraries)
    sourceSets["main"].java.srcDir("../generated/kotlin")
    sourceSets["main"].jniLibs.srcDir("../generated/jniLibs")
}

dependencies {
    // UniFFI-generated Kotlin uses JNA; the @aar variant bundles its native libs. `api` so the
    // generated `uniffi.hop_ffi.*` types stay usable from consumers (the app references them).
    api("net.java.dev.jna:jna:5.14.0@aar")

    // The bearer exposes Compose snapshot state (mutableStateOf/…), so the runtime is part of the
    // driver's public surface — `api` so consuming UI observes the same snapshot system.
    api(platform("androidx.compose:compose-bom:2024.06.00"))
    api("androidx.compose.runtime:runtime")

    // Cloud relay bearer: WebSocket (path B, wss:// → Cloud Run) + the okio ByteString it speaks.
    api("com.squareup.okhttp3:okhttp:4.12.0")

    implementation("androidx.core:core-ktx:1.13.1")
}
