/* libhop — the Hop client SDK + bearer contract. GENERATED by cbindgen; do not edit. */

#ifndef HOP_H
#define HOP_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Which side opened a bearer link (the Noise role). Mirrors hop-core's internal `Role`.
typedef enum HopLinkRole {
    // We dialed out (BLE central / TCP connect / Wi-Fi inviter) → Noise initiator.
    HopLinkRole_Dialer = 0,
    // A peer connected in (peripheral / listener / invitee) → Noise responder.
    HopLinkRole_Acceptor = 1,
} HopLinkRole;

// A running Hop node the host drives. Thread-safe (interior `Mutex`), handed to
// the foreign side as a reference-counted object.
typedef struct HopNode HopNode;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Open a node with persistent storage at `db_path` (UTF-8 C string), a saved 32-byte identity
// `secret` (pass NULL/0 for a fresh identity), and a 32-byte `app_secret` (NULL/0 = open fabric).
// Returns an owning handle to free with `hop_node_free`, or NULL on a NULL/invalid `db_path`.
const struct HopNode *hop_node_open(const char *db_path,
                                    const uint8_t *secret,
                                    uintptr_t secret_len,
                                    const uint8_t *app_secret,
                                    uintptr_t app_secret_len);

// Create a node with a fresh identity and ephemeral (in-memory) storage. Free with `hop_node_free`.
const struct HopNode *hop_node_new(void);

// Free a node handle returned by any constructor. Safe to pass NULL.
void hop_node_free(const struct HopNode *node);

// Write this node's 32-byte address into `out` (must have room for 32 bytes). False on NULL.
bool hop_node_address(const struct HopNode *node, uint8_t *out);

// Advance time: expire adverts, retransmit unacked bundles, prune dedup. Call ~1 Hz.
void hop_node_tick(const struct HopNode *node, uint64_t now_ms);

// A bearer link came up. `role` = which side dialed (the Noise initiator/responder selector).
void hop_link_up(const struct HopNode *node, uint64_t link, enum HopLinkRole role);

// One frame of opaque bytes arrived on `link`.
void hop_bytes_received(const struct HopNode *node,
                        uint64_t link,
                        const uint8_t *data,
                        uintptr_t len);

// A bearer link dropped.
void hop_link_down(const struct HopNode *node, uint64_t link);

// Drain queued outbound packets. Synchronously invokes `sink(ctx, link, bytes_ptr, bytes_len)`
// once per packet during this call — this is the POLL model; core never pushes asynchronously.
// The byte pointer is valid only for the duration of each `sink` call; copy what you keep.
void hop_drain_outgoing(const struct HopNode *node, void (*sink)(void *ctx,
                                                                 uint64_t link,
                                                                 const uint8_t *bytes,
                                                                 uintptr_t len), void *ctx);

// Subscribe the directory to a service `topic` (UTF-8 C string).
void hop_subscribe(const struct HopNode *node, const char *topic);

// Publish this node's prekey advert (DESIGN.md §25) so peers can seal forward-secret messages to
// us; it gossips on link-up. Call once after opening (and after the first `hop_node_tick` sets a
// real clock, else the advert is judged expired). Returns true on success.
bool hop_publish_prekey(const struct HopNode *node);

// Drain newly-received messages (poll model). Invokes
// `sink(ctx, from32, content_type_cstr, body_ptr, body_len, hops, created_at_ms)` once per message
// during this call. `from` points at 32 address bytes; `content_type` is a NUL-terminated UTF-8
// string; `body` is `body_len` bytes — all valid only for the duration of each `sink` call.
void hop_poll_inbox(const struct HopNode *node, void (*sink)(void *ctx,
                                                             const uint8_t *from,
                                                             const char *content_type,
                                                             const uint8_t *body,
                                                             uintptr_t body_len,
                                                             uint8_t hops,
                                                             uint64_t created_at), void *ctx);

// Send a message to the 32-byte address `dst` — untraceable by default (DESIGN.md §39).
// `content_type` is a UTF-8 C string (e.g. "text/plain"); `body`/`body_len` is the payload. If
// `request_ack`, a private delivery confirmation is requested. On success writes the 32-byte
// bundle id into `out_id` (room for 32 bytes, may be NULL to ignore) and returns true.
bool hop_send_message(const struct HopNode *node,
                      const uint8_t *dst,
                      const char *content_type,
                      const uint8_t *body,
                      uintptr_t body_len,
                      bool request_ack,
                      uint8_t *out_id);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HOP_H */
