#!/usr/bin/env bash
# Discover each device's stable base58 self-address and write testkit/addrs.env.
# Run after a (re)deploy. Identity is device-seed-derived, so addresses are durable across wipes.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

OUT="$HERE/addrs.env"
echo "# generated by refresh-addrs.sh — name->addr map for the test harness" > "$OUT"
for id in $(dev_ids); do
  a=$(tk_self_addr "$id")
  if [ -n "$a" ]; then
    echo "ADDR_$id=$a" >> "$OUT"
    printf '%-6s %s  (%s, %s)\n' "$id" "$a" "$(dev_platform "$id")" "$(dev_transport "$id")"
  else
    echo "# ADDR_$id=   (NOT FOUND — device offline / app not launched / not yet deployed)" >> "$OUT"
    printf '%-6s MISSING\n' "$id"
  fi
done
echo "wrote $OUT"
